### ISSUE TITLE
Merge of gonzalo-bulnes/dredd-hooks-ruby

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd-hooks-ruby#13]
Hey @gonzalo-bulnes,

I noticed you did a huge amount of amazing work in your fork. I'm sorry we didn't have much time to merge your pull requests, but it doesn't mean we're not interested in your contributions!

We have this Aruba/Cucumber based integration test-suite so I feel very confident and I'm more than happy to give you maintainer rights to this repository. You could continue your work here and kind of help yourself when needed. We will do our best on our part. What do you think? Would you be interested?

Adam

**Comment by netmilk** [comment]
I'd be happy to add you to rubygems too, of course.

**Comment by gonzalo-bulnes** [comment]
Hi @netmilk!

I'd be happy to continue here, it would simplify the general workflow, and I'm really glad to receive your trust. I'm very confident in the test suite too, and in the way the gem API is defined by its Cucumber features. (Indeed, I like a lot the way I've seen your team using Cucumber as a cross-project cross-languages documentation and test tool.)

I'll continue doing my best to keep each PR readable and self-contained so I can ping you to discuss decisions if needed. Likewise, please ping anytime if specific coordination is needed, or if anything time-sensitive happens (I'll do my best to respond quickly).

Also, I'm comfortable with Rubygems too, and I'd be glad to get access to release the gem. Be assured that I'll reach out to you or @honzajavorek if in doubt about your usual workflows!

Gonzalo

**Comment by gonzalo-bulnes** [comment]
Concretely, once I have your green light, I'll start merging the PR I merged in my fork, in the same way I did there to keep the whole history readable.

**Comment by netmilk** [comment]
@gonzalo-bulnes I'm super excited you're willing to take care of it! [I invited you](https://github.com/apiaryio/dredd-hooks-ruby/invitations) to collaborators here on GitHub. I added you as an owner of the gem as well. Would you mind confirming you have access to both places? :)

**Comment by gonzalo-bulnes** [comment]
Hi @netmilk! I confirm I have access to both this repository and Rubygems (awesome :D). l'll get started updating the repo in the next few days. Thank you!

**Comment by netmilk** [comment]
@gonzalo-bulnes I thank you! :) I'll leave this issue open until it's actually all merged.

Just a quick question: Did you actually plan any breaking changes to the Ruby Hooks API?

**Comment by gonzalo-bulnes** [comment]
Yes, although none of them is critical, I've been thinking that there would be value in introducing the following three breaking changes (in order of importance):
1. Using [Thor](http://whatisthor.com/) to build the CLI would imply to move the starting command from `dredd-hooks-ruby` to `dredd-hooks-ruby start` (impact on Dredd) - details below.
2. Moving `DreddHooks::Methods` to `DreddHooks::DSL` (or `Dredd::Hooks::DSL`) would change the requirement in the hooks files
3. Moving to `Dredd::Hooks` _could_ be followed by a gem name change (or not)

So far, I've only performed backward-compatible changes (steps 1 and 2 of [this roadmap](https://github.com/apiaryio/dredd-hooks-ruby/issues/5#issuecomment-213986901)). I'm finishing the second part (renaming things in a backward-compatible manner) and am open to discuss the plans for the third step (indeed, the 3 changes are independent).

Here are my views so far (it's a bit long, but there is no hurry, feel free to comment when you're ready):

**1. About using Thor**

Thor provides a light syntax to create thoroughly documented CLI with minimal effort. Even if the CLI is minimal and should probably be kept small, I would make the change while it's easy to do.

In this [example](https://github.com/gonzalo-bulnes/kata-images_gallery_generator/blob/v1.1.0/lib/images_gallery/cli.rb#L8-L19), running `images_gallery generate` with missing arguments displays the `generate` command help, while running `images_gallery help` displays all the available commands, it's pretty good user experience and the code is clear and maintainable.

But there is no way to run the bare `dredd-hooks-ruby` and skip the command name, it must be `dredd-hooks-ruby <something>` (and I would choose `start`).

**2. About renaming the Methods/DSL module**

Domain-specific languages are pretty common in Ruby. Referring to them as  `DSL` modules is not uncommon (see [Capybara](https://github.com/jnicklas/capybara#using-the-dsl-elsewhere), [RSpec](https://github.com/rspec/rspec-core/blob/v3.5.1/lib/rspec/core/dsl.rb)), and doing so has, in my opinion, two benefits:
- it is unambiguous for who knows what a DSL is (and in particular it makes explicit that the method names/signatures are focused on the end-user and should be considered as a whole)
- "Ruby DSL" points clearly to the right documentation to who doesn't know what a DSL is - much more clearly than anything "Ruby methods" can do

Note, however, that `DSL` is not used everywhere either: [Factory Girl](https://github.com/thoughtbot/factory_girl/blob/v4.7.0/lib/factory_girl/syntax/default.rb) is a good counter-example and goes with `Syntax`.

**3. About renaming the main module to Dredd::Hooks**

Is more of a personal preference for consistent naming schemes, and a minor issue. Dredd being the name of a tool, and Dredd::Hooks and extension, the Ruby usage suggests to use `dredd-hooks`, `Dredd::Hooks`, `lib/dredd/hooks`... just like `FactoryGirl::Rails` or `RSpec::Core` (or `Dredd::Rack`!).

Doing so could imply either renaming the gem to `dredd-hooks` (so the `lib/dredd/hooks.rb` is loaded by default), or performing the naming trick of requiring `lib/dredd/hooks.rb` from the automatically loaded `lib/dredd_hooks.rb`. (It's not as bad as it seems - pretty OK I would say.)

I would rename the module and perform one of the two implied changes (probably the latter? I'm not fond of the idea of renaming the gem), but it's more of a personal call.

**Comment by gonzalo-bulnes** [comment]
Here are the first few, I'll proceed by small batches over the next few days. : )

**Comment by netmilk** [comment]
@gonzalo-bulnes Thanks for the elaboration! :) 

I'm sorry, but I think there will be a problem with the migration to Thor. The command-line syntax used by Dredd to spin up the hook handler is actually a uniform API used for all the hook workers (python, go, php etc..). The syntax is:

```
$ dredd-hooks-handler ./file1.lang ./file2.lang ./file3.lang ./files/*.lang ...
```

Any change of this syntax would mean to change the CLI syntax of all the hook handlers and the way how [Dredd's starting handlers](https://github.com/apiaryio/dredd/blob/master/src/hooks-worker-client.coffee#L163).

**Comment by gonzalo-bulnes** [comment]
@netmilk, fair enough! And I agree totally that as a common interface it shouldn't be changed.

If any new CLI requirements appear in the future, maybe we can evaluate the possibility of shipping two binaries (one delegating to the other in order to expose the hooks handlers API), but it seems unlikely and I don't think it would be wise or useful to duplicate that API until having compelling reasons to do so.

I'll manage the arguments count, content and help manually, it's not such a big deal for a few commands.

**Comment by gonzalo-bulnes** [comment]
We're up-to-date with respect to [gonzalo-bulnes/dredd-hooks-ruby](https://github.com/apiaryio/dredd-hooks-ruby).

I think we can close this issue and continue the conversation about potential breaking changes in #5 (which is focused on getting the gem towards **v1.0.0**), what do you think @netmilk?

**Comment by netmilk** [comment]
@gonzalo-bulnes Thank you for the amazing work here!
