### ISSUE TITLE
Aruba should be up to date

### ISSUE THREAD

**Issue by gonzalo-bulnes** [apiaryio/dredd-hooks-ruby#26]
Please see [this comment][src] and the few next ones.

  [src]: https://github.com/apiaryio/dredd-hooks-ruby/pull/25#issuecomment-260293852

**Comment by honzajavorek** [comment]
The test suite is copied to each of the projects and it's not a real dependency (as in something which can be installed or is a git submodule), so it can be easily modified in one project and not the others. On the other hand, we definitely want to keep them the same as that's the whole purpose of the BDD test suite.

I'd propose we update Aruba in one of the reference hook projects - either in Ruby (@gonzalo-bulnes) or Python (me or @w-vi). Ideally, new Aruba would mean just changes in how the test suite is written, not changes in the code of the actual hooks handler under test. Once we're able to get it passing, we would then take the changes made to the tests and port them to [`dredd-hooks-template`](https://github.com/apiaryio/dredd-hooks-template). Then, we would make Pull Requests with the changes to the all other projects (cc @ddelnano) in a similar manner I distributed required changes in `.travis.yml` in the past (https://github.com/apiaryio/dredd-hooks-ruby/pull/11, https://github.com/snikch/goodman/pull/10, https://github.com/ddelnano/dredd-hooks-php/pull/22, https://github.com/ungrim97/Dredd-Hooks/pull/2, https://github.com/apiaryio/dredd-hooks-python/pull/19).

What do you think @gonzalo-bulnes, @netmilk? Gonzalo, would you like to pioneer the Aruba upgrade?

**Comment by ddelnano** [comment]
👍

**Comment by gonzalo-bulnes** [comment]
Hi everyone!

Thoughts:
> [...] new Aruba would mean just changes in how the test suite is written, not changes in the code of the actual hooks handler under test.

Yes, definitely. Any required change in the hook code should be regarded with great suspicion.

> I'd propose we update Aruba in one of the reference hook projects [...] then take the changes made to the tests and port them to `dredd-hooks-template` [t]hen [...] make Pull Requests with the changes to the all other projects [...]

Sounds good to me 👍 

> Gonzalo, would you like to pioneer the Aruba upgrade?

Okay @honzajavorek  I'll give it a try! : )

**Comment by gonzalo-bulnes** [comment]
It seems that updating Aruba is going to be much simpler than I expected, in a nutshell:

- @netmilk is [this `@debug` tag][tag] used for anything at all in production or test environment?
- If the tag is dispensable (as I think it is) then the features failures were not caused by a change of behaviour in the Aruba API, but actually by a the addition of a new feature which involves a `@debug` tag and has nothing to do with our test suite - in other terms it's just a name clash, and the name that is clashing is not even something we're actually using.

The long story:

I spent some time wandering around the Aruba docs, and wondering what exactly the `@debug` tag was doing, without much success. I then decided to try updating Aruba by steps, just to get an idea of how bad things were, and it failed straight away at v0.7.0 (instead of v0.9.x as I [expected][expectation]).

The v0.7.0 release of Aruba introduced a lot of [refactoring and features][pr] (more than I could fit in my head). That's when I went for `git bisect` ([changelog][bisect]).

Our test suite started failing [when Aruba added support for a feature that uses an `@debug` tag][fail]. I quickly checked that our `@debug` tag was actually not doing anything visible when we were using Aruba v0.6.2, but started displaying the Dredd hooks output when moving to Aruba v0.7.0 - and causing the test to fail with messages in the lines of:

```cucumber
[...]

And the output should contain:
      """
      Yay! Failed in ruby!
      """
      expected "This is the debug launcher on STDOUT. If this output is unexpected, please check your setup.This is the debug launcher on STDERR. If this output is unexpected, please check your setup." to string includes: "Yay! Failed in ruby!" (RSpec::Expectations::ExpectationNotMetError)
```

What I understand, is that `@debug` in our features was used when writing them (I mean locally), but had no particular meaning for Aruba at that point. (Aruba did not support anything related to that tag before v0.7.0 and Cucumber itself doesn't seem to assign it any particular meaning either.) It was just a tag.

Somehow it stayed in place, and did not cause any trouble (nor did anything at all - unless I'm missing something) until Aruba just decided to use the exact same tag name for a new feature of theirs.

Removing the tag causes no harm to our test suite when using Aruba v0.6.2 and allows seamless updates up to v0.14.2 (the [latest release of Aruba to date][latest]).

I'm going to create a PR for this, and if the timeline/explanation makes sense to you @honzajavorek, I think we can go forward with the update! The [spike is here for easier review][review] : )

  [review]: https://github.com/apiaryio/dredd-hooks-ruby/compare/v0.1.2...gonzalo-bulnes:spike-update-aruba?expand=1
  [pr]: https://github.com/cucumber/aruba/pull/257
  [latest]: https://github.com/cucumber/aruba/releases/tag/v0.14.2
  [fail]: https://github.com/cucumber/aruba/commit/959de81dd03f6ab12e770fb920ab718e0a53ec96#diff-61ac4071b2f084ddaf80ca6b4188c97cR50
  [bisect]: https://github.com/gonzalo-bulnes/dredd-hooks-ruby/commit/bb041ed9be7705c1b16ae3a74f8a0a2a49a613a2
  [expectation]: https://github.com/apiaryio/dredd-hooks-ruby/pull/25#issuecomment-260162898
  [tag]: https://github.com/apiaryio/dredd-hooks-template/blob/7ab9ec9f2910fffd7144b119c73ddb9b193a4c6d/features/execution_order.feature#L22

**Comment by honzajavorek** [comment]
I don't know exactly what's the history behind the `@debug` tag (@netmilk's input welcome), but when I was previously replying with a link to the [repo of the template](https://github.com/apiaryio/dredd-hooks-template/), I noticed this in the list of issues: https://github.com/apiaryio/dredd-hooks-template/issues/2

**Comment by gonzalo-bulnes** [comment]
I'm not sure either, and I'm a bit confuse about both using `@announce` (or `@debug` for that purpose) in the "production test suites" (if that makes any sense? - I mean: on a permanent basis, vs. for debug purpose).

First of all, the `@announce` tag is not necessary to test the content of the output - see how similar the [`@annouce` feature][ann] and the ["output" feature][out] are.

  [ann]: https://github.com/cucumber/aruba/blob/master/features/testing_frameworks/cucumber/announce.feature
  [out]: https://github.com/cucumber/aruba/blob/master/features/testing_frameworks/cucumber/steps/command/output.feature

Besides, while I confirm that `@announce` tag does work fine in our test suite (as @w-vi was [suggesting][issue]), I think it is much more verbose than we need on a daily basis and I'm not sure that level of detail would really help anyone new to the hooks to understand them better. (I think the features themselves are pretty clear.)

With that in mind, unless I am missing a benefit of making these details visible, I would not replace `@debug` by `@announce` in our case, I would just remove `@debug`.

If debug is needed, however, I would definitely go with `@announce` - and I'll mention it in the corresponding issue : )

  [issue]: https://github.com/apiaryio/dredd-hooks-template/issues/2

**Comment by honzajavorek** [comment]
I think the only missing piece is then to ask @netmilk what was the original purpose of `@debug` in this case. Just to be sure. Then I'd say it's good to go :)

**Comment by netmilk** [comment]
@gonzalo-bulnes @honzajavorek the `@debug` tag is [an Aruba thing](https://github.com/cucumber/aruba/blob/master/features/testing_frameworks/cucumber/steps/command/debug.feature) and can be removed from the features here. I recall I left it there undocumented because I had hard time to find it initially.

**Comment by gonzalo-bulnes** [comment]
Hi @honzajavorek! Just waiting for you green light : )

**Comment by honzajavorek** [comment]
I approve! Thanks!

**Comment by gonzalo-bulnes** [comment]
@ddelnano For info, we're moving to [dredd-hooks-template](https://github.com/apiaryio/dredd-hooks-template/pull/9) : )

**Comment by ddelnano** [comment]
@gonzalo-bulnes just to be clear all we need to do is remove the `@debug`??  I didn't know what to expect for this change but I was expecting it to be a little more involved than that.

**Comment by gonzalo-bulnes** [comment]
Yes @ddelnano!

I was also expecting _a lot_ more than that -I thought that how Aruba handles output had changed over time- but it happens that removing the `@debug` tags is all that's needed to be able to use newer versions of Aruba (see [this previous comment for a more detailed explanation][expl]).

  [expl]: https://github.com/apiaryio/dredd-hooks-ruby/issues/26#issuecomment-271135646

Notice that replacing `@debug` by `@announce` would also be fine, but the features are actually more readable without that extra output. (`@announce` is really good for debugging purpose however!)

It ended up being quick and easy : )

**Comment by honzajavorek** [comment]
This is a tracking issue for porting the changes to each of the hook repositories: https://github.com/apiaryio/dredd-hooks-template/issues/16
