### ISSUE TITLE
Raising NoMethodError inside a hook block causes a hard-to-debug error message

### ISSUE THREAD

**Issue by nicolasiensen** [apiaryio/dredd-hooks-ruby#27]
If you raise, for example, a `StandardError` inside of a `before_each` block:

```ruby
require "dredd_hooks/methods"
include DreddHooks::Methods

before_each do |transaction|
  raise StandardError
end
```

When you run Dredd you will see the expected error message:

```shell
$ info: Hooks handler stderr: /Users/nicolasiensen/.../dredd_hooks.rb:5:in `block in <top (required)>': StandardError (StandardError)
```

However, if the exception being raised inside of the `before_each` block is a `NoMethodError`:

```ruby
require "dredd_hooks/methods"
include DreddHooks::Methods

before_each do |transaction|
  raise NoMethodError
end
```

Then the error message is completely misleading:

```shell
$ info: Hooks handler stderr: /Users/nicolasiensen...dredd_hooks/server/events_handler.rb:24:in `rescue in block in handle': Unknown hook: before_each (DreddHooks::UnknownHookError)
```

I've spent hours debugging `dredd-hooks-ruby` code trying to understand why `before_each` was not a valid hook, only to discover later that my code was raising `NoMethodError` inside of the hook block 🤦‍♂️

**Comment by gonzalo-bulnes** [comment]
You are totally right @nicolasiensen, the scope of rescuing the `NoMethodError` exception was way too large. (My bad.)
