### ISSUE TITLE
More documentation required

### ISSUE THREAD

**Issue by JakeSchoermer** [apiaryio/dredd-hooks-ruby#3]
Hi there,

I've just started integrating dredd and apiary with an existing Rails app, but am having trouble using this gem given the lack of documentation and examples on the usage of this gem. I'd also like to use dredd with existing FactoryGirl factories so it would be great to figure out this can be done.

Happy to work with you to make this happen, both for my benefit and that of other users.

Cheers,

Jake Schoermer

**Comment by netmilk** [comment]
HI @Schermy,

the documentation is part of the core [Dredd repo](https://github.com/apiaryio/dredd) and it's hosted [here](http://dredd.readthedocs.org/en/latest/hooks-ruby/) on Read The Docs. Is this what you are looking for? Are you looking for any other information? I'm happy to help you and even more happy to see any contributions. :)

Adam

**Comment by w-vi** [comment]
@Schermy also have a look on a bit dated but still valid dredd rails example https://github.com/apiaryio/dredd-test-rails

**Comment by honzajavorek** [comment]
@JakeSchoermer I assume http://dredd.readthedocs.io/en/latest/hooks-ruby/ was what you were looking for. I'll close this dated issue now, feel free to file a new one, specific to any further needs of yours.
